# Generated by Django 3.2.4 on 2021-06-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Content',
        ),
    ]
