# Generated by Django 3.2.4 on 2021-06-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_content_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
