# Generated by Django 3.2.4 on 2021-06-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='posted_on',
            field=models.DateTimeField(),
        ),
    ]
