# Generated by Django 3.2.4 on 2021-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_content_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='names',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
    ]
