# Generated by Django 3.2.4 on 2021-06-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_content_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='dates',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
    ]
