# Generated by Django 3.2.4 on 2021-06-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_content_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='countries',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
    ]
