# Generated by Django 3.2.4 on 2021-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_auto_20210630_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='percentile',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
