# Generated by Django 3.2.4 on 2021-06-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_content_percentile'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
