# Generated by Django 3.2.4 on 2021-07-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_content_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
